TITLE = "Comet Hunter API"

CLIENT_BASE_URL = "http://127.0.0.1:8080"

PROCESS_LOOKBACK_BUFFER_HOUR = 1
PROCESS_MIN_OBSERVATION_GAP_MINUTES = 8
PROCESS_MAX_OBSERVATION_GAP_MINUTES = 16
PROCESS_TIMEOUT_MINUTES = 5
PROCESS_MAX_WORKERS = 4
PROCESS_KERNEL_SIZE = 5

METADATA_TIMEOUT_SECONDS = 15

DOWNLOAD_MAX_WORKERS = 4
DOWNLOAD_TIMEOUT_SECONDS = 60

INGESTION_CYCLE_INTERVAL_MINUTES = 5

PIPELINE_PROCESS_PADDING_HOURS = 12

MAX_PROCESSING_ATTEMPTS = 2
MAX_DOWNLOADING_ATTEMPTS = 2